{% set name = "sncosmo" %}
{% set version = "2.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0320170c84cf281063aae9364d89dd2436b7e0f81f2dd28e6f0f2284f07dbe58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - astropy >=5.0
    - extinction >=0.4.6
    - h5py >=3.11
    - looseversion >=1.0.0
    - pyyaml >=6.0.1
    - scipy >=1.10.0

test:
  imports:
    - sncosmo
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/sncosmo/sncosmo
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python library for supernova cosmology
  description: |
    SNCosmo synthesizes supernova spectra and photometry from SN models,
    and has functions for fitting and sampling SN model parameters given
    photometric light curve data. It includes supernova models such as SALT2,
    MLCS2k2, Hsiao, Nugent, PSNID, SNANA and Whalen models, as well as a
    variety of built-in bandpasses and magnitude systems, and provides
    convenience functions for reading and writing commonly used data formats.
    The library is extensible, allowing user-defined models, bandpasses,
    and magnitude systems.
  doc_url: http://sncosmo.readthedocs.io/
  dev_url: https://github.com/sncosmo/sncosmo

extra:
  recipe-maintainers:
    - kbarbary
    - mwcraig
    - kboone
    - benjaminrose
    - jpierel14
    - rbiswas4
