appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: snJkgaf6vV9mWH4SmGUZ4iEUsZ5Z+WqmBzbM93Tmt+geGv941qkMlfPgYugaE+hrBXJtk4eqwugiQrtqu217o+3qFJB6AeX1k60Gbh2AiBPiqbjksz0CwEq67f2uuaGEohSC1op32ROdh+at2PXmtgxY4NSYGfQcX97HZxXoYK3rXhucXOZjqErcyVNfGoEgk0lGHsGxW0LFbBjwcIOlLpgDguin4D4f9/Wf9KQg2mgvpijGOjAqUOaEmNll2/huiuZtpCoIqMPU8ys3e+GSg6lqdp73NqHRHAnCtLf78EGQq6Zz9+m8bcmUdhbVqYWUTeXP4AJs6/g/6Q1VtwSIiOXULgqg8tThGXHYNn0mvRKbl8MvGfCOdcV23AUS1ZD/Gvbzvs1Fj3Tq0Y0REALwV6nQP6ZCq8Np+Aoj8lWzQ7+Z8T6i+RZb8geddfLz8LK3wO36q44wGHHZlLoD+WLlMRsWh7D5TJNCkWadchrLWgS6PVSIQkJ66fyJ5EUEIMffRSeLcoY61AGIMdYyaR3Tf4Tca1LeR4ysLS1u0GvkbTZdRj/wc+tyWWfbrTuGTS4MUIdOVOayIiLn7xAu8apy/MwKplb1OrJI+LmuKhNEOpmn9l0ufYLfqE3gfHsaLeXxBvZWxq0+R1DU2dcv0bWTi3V+z2K51PBH71o+4iv5DAY=}
provider:
  win: azure
